### ISSUE TITLE
Crash on Line #158

### ISSUE THREAD

**Issue by fwhenin** [s-aska/KeyClip#5]
depending on the provisioning profile I use, sometimes this line crashes

https://github.com/s-aska/KeyClip/blob/master/KeyClip/KeyClip.swift#L158

Not sure what I'm doing wrong

**Comment by s-aska** [comment]
If there is a sample project to crash you can investigate.
Xcode version is 6.1? (swift 1.1)

**Comment by fwhenin** [comment]
Xcode 6.1, Swift 1.1

**Comment by fwhenin** [comment]
crashes on that line on release builds

**Comment by s-aska** [comment]
Thanks
I release 1.1.3. ( -Onone )
please update carthage.

```
carthage update
```

https://github.com/s-aska/KeyClip/commit/0cb8736324cc9dd6aa1eec1e9a6aa111aef6f52a

**Comment by AlexCatchpole** [comment]
I'm still getting this error, even after the update.

**Comment by s-aska** [comment]
Is there such as error messages and screenshots?
I am in need of detailed information.
Because the same error in my environment does not occur.

**Comment by AlexCatchpole** [comment]
It's fine when running on the simulator but when it comes to running on an IOS device in both release and debug builds it crashes on line #158 when saving a string.

As my device is not available for testing right now I can't get an exact error message but I believe it was an error message along the lines of 
`cannot assign to the result of this expression`

The code I used to save is
`KeyClip.save("pinCode", string: finalCode)`

Changing my provisioning profile does not seem to affect it either.

**Comment by fwhenin** [comment]
@AlexCatchpole I Unfortunately, had to switch and use another Wrapper. I liked the simplicity of KeyClip, but I couldn't rely on it. 

@s-aska I would get 'EXC_BAD_ACCESS' on that line, not sure what else to tell you? a screenshot wouldn't help

**Comment by AlexCatchpole** [comment]
@fwhenin 
Oh yes that's the error! Sorry I must have forgot, it works on the simulator but not on an actual device. May I enquire what wrapper you are using now? I'm in desperate need of storing sensitive information.

**Comment by fwhenin** [comment]
https://github.com/jrendel/SwiftKeychainWrapper

**Comment by s-aska** [comment]
Thank you for detailed information.
Probably can not be rewritten query after SecItemUpdate.
I've prepared a new version. (1.2.0)
https://github.com/s-aska/KeyClip/commit/290a22e4da702c0d7b9777e5785092ec46931aea

**Comment by AlexCatchpole** [comment]
That's fixed it as far as I can tell.
Thanks!

**Comment by s-aska** [comment]
It was good. :)
Sorry to have kept you waiting.
